version: "3.2"
services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - ./sites/:/var/www/html/
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./sites/:/var/www/html/
      - ./apache/conf/:/usr/local/apache2/conf/
      - ./apache/logs/:/var/apache/logs/
  mysql:
    image: mysql:5.7
    networks:
      - backend
    ports:
      - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_PASSWORD=root

volumes:
  mysql_db:

networks:
  frontend:
  backend: